// This file is automatically generated.
// Please do not modify it manually.
//
// This file is used to store the Firebase configuration for your app.
// It is used by the Firebase SDK to connect to your Firebase project.

export const firebaseConfig = {
  projectId: "studio-4101012908-39568",
  appId: "1:363636307409:web:2aea1126f3ac3fcb80dcf0",
  apiKey: "AIzaSyDHSE63D8ssSvXfMks7Yz9fOBgCdY8agC8",
  authDomain: "studio-4101012908-39568.firebaseapp.com",
  messagingSenderId: "363636307409"
};
